# Service Kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: discovery
spec:
  ports:
    - port: 9092
      targetPort: 9092
      #protocol: TCP
      #- name: prom-kalfa
      #  port: 9308
      #  targetPort: 9308
  selector:
    app: kafka
---
# Kafka deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_CREATE_TOPICS
              value: bmp-service-chain:1:1
            - name: KAFKA_CONNECTIONS_MAX_IDLE_MS
              value: "-1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:31092"
          ports:
            - containerPort: 9092
              #- containerPort: 9308
      restartPolicy: Always
---
# Zookeeper service
apiVersion: v1
kind: Service
metadata:
 labels:
   app: zookeeper
 name: zookeeper
 namespace: discovery
spec:
 ports:
 - name: zookeeper-cluster
   port: 2181
   targetPort: 2181
   #- name: zookeeper-follower
   #  protocol: TCP
   #  port: 2888
   #  targetPort: 2888
   #  nodePort: 42888
   #- name: zookeeper-leader
   #  protocol: TCP
   #  port: 3888
   #  targetPort: 3888
   #  nodePort: 43888
 selector:
   app: zookeeper
---
# Zookeeper Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: discovery
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
    spec:
      containers:
      - image: wurstmeister/zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181
          #- containerPort: 2888
          #- containerPort: 3888
      restartPolicy: Always
